Repository babajka/babajka-backend, pull requests merged in 2018-06, with the labels that each got.

#29 Update dependencies
  .travis.yml
  package-lock.json
  package.json
Labels: tools

#28 Collections API improvements
  package-lock.json
  package.json
  pm2-config.json
  public/index.html
  src/api/article/article.model.js
  src/api/article/collection/controller.js
  src/api/article/collection/model.js
  src/api/article/collection/tests.js
  src/api/article/controller.js
  src/api/user/model.js
  src/config/index.js
  src/db/articleCollections.json
  src/db/init.js
  src/db/initProdDiaries.js
Labels: feature, fix

#30 Permissions, HTTPS, BABAJKA_SECRET
  package.json
  pm2-config.json
  src/api/user/model.js
  src/config/config.json
  src/config/index.js
  src/constants/permissions.js
  src/db/articleBrands.json
  src/db/scripts/grantPermissions.js
  src/db/scripts/initProdDiaries.js
Labels: feature, fix

#31 Article Schema, publishAt changes
  package-lock.json
  package.json
  src/api/article/article.model.js
  src/api/article/author/tests.js
  src/api/article/brand/model.js
  src/api/article/collection/controller.js
  src/api/article/collection/model.js
  src/api/article/collection/tests.js
  src/api/article/controller.js
  src/api/article/controller.tests.js
  src/api/article/localized/model.js
  src/api/article/localized/tests.js
  src/api/specials/diary/model.js
  src/api/user/model.js
  src/api/user/tests.js
  src/auth/index.js
  src/auth/tests.js
  src/constants/permissions.js
  src/db/data/articleBrands.json
  src/db/data/articleCollections.json
  src/db/data/articles.json
  src/db/data/diary.json
  src/db/data/users.json
  src/db/scripts/grantPermissions.js
  src/db/scripts/initAll.js
  src/db/scripts/initProdDiaries.js
  src/db/scripts/setPassword.js
  src/utils/testing.js
  src/utils/validation.js
  src/utils/validation.tests.js
Labels: fix

#32 Handling Article images
  public/test/images/seattle.jpg
  src/api/article/article.model.js
  src/api/article/author/tests.js
  src/api/article/collection/tests.js
  src/api/article/controller.tests.js
  src/api/article/index.js
  src/api/article/localized/tests.js
  src/db/data/articles.json
  src/utils/validation.js
Labels: feature
